import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { AuthFlowError } from "../../dist-electron/auth/auth-contracts.cjs";
import { GamePackageDownloadManager, GamePackageFlowError, parseGamePackageEnvelope, verifyDownloadedGamePackage } from "../../dist-electron/games/game-package-download.cjs";
import { LocalDatabase } from "../../dist-electron/persistence/local-database.cjs";

const roots = [];
const databases = [];
const gameId = "game-1";
const payloadJson = JSON.stringify({ schemaVersion: 1, game: { id: gameId, organizationId: "organization-a", competitionId: "competition-1", competitionName: "League", seasonName: "2026-27", phaseName: "Regular", roundLabel: "Round 1", scheduledDate: "2026-08-26", scheduledTime: "20:00", scheduledAt: null, venue: null }, settings: { game_mode: "SIMPLE", min_players: 5, max_players: 12, starting_players: 5, regulation_periods: 4, regulation_period_seconds: 600, overtime_seconds: 300, tie_allowed: false, winner_required: true }, teams: [{ side: "HOME", id: "home", name: "Home", logoUrl: null, players: [], staff: [] }, { side: "AWAY", id: "away", name: "Away", logoUrl: null, players: [], staff: [] }] });
const payloadHash = createHash("sha256").update(Buffer.from(payloadJson, "utf8")).digest("hex");
function envelope(overrides = {}) { return { packageId: "package-v1", gameId, packageVersion: 1, packageSchemaVersion: 1, publishedAt: "2026-08-25T12:00:00.000Z", payloadJson, payloadHash, ...overrides }; }
function database() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "komocontrol-download-")); roots.push(root); const db = new LocalDatabase({ databasePath: path.join(root, "komocontrol.sqlite"), migrationsDirectory: path.resolve("electron/migrations"), backupDirectory: path.join(root, "backups") }); db.initialize(); databases.push(db); return db; }
afterEach(() => { vi.restoreAllMocks(); for (const db of databases.splice(0)) db.close(); for (const root of roots.splice(0)) fs.rmSync(root, { recursive: true, force: true }); });

describe("KomoControl GamePackage download", () => {
  it("verifies exact UTF-8 payload bytes", () => { expect(verifyDownloadedGamePackage(gameId, envelope()).payloadJson).toBe(payloadJson); });
  it("accepts authoritative empty-string nullable metadata and stores it safely", async () => { const payload = JSON.parse(payloadJson); payload.game.phaseName = ""; payload.game.roundLabel = ""; payload.game.scheduledAt = ""; payload.game.venue = ""; payload.teams[0].logoUrl = ""; const exactPayload = JSON.stringify(payload); const exactHash = createHash("sha256").update(Buffer.from(exactPayload, "utf8")).digest("hex"); const store = database(); const result = await new GamePackageDownloadManager({ downloadGamePackage: async () => envelope({ payloadJson: exactPayload, payloadHash: exactHash }) }, store).download("token", gameId); expect(result.status).toMatchObject({ gameId, availableOffline: true, currentVersion: 1 }); expect(JSON.stringify(result.status)).not.toMatch(/payload|hash/i); store.close(); });
  it.each([undefined, 42, {}])("rejects non-string nullable metadata: %s", (invalid) => { const payload = JSON.parse(payloadJson); payload.game.venue = invalid; const invalidPayload = JSON.stringify(payload); const invalidHash = createHash("sha256").update(Buffer.from(invalidPayload, "utf8")).digest("hex"); expect(() => verifyDownloadedGamePackage(gameId, envelope({ payloadJson: invalidPayload, payloadHash: invalidHash }))).toThrow(GamePackageFlowError); });
  it("rejects hash mismatch before local storage", async () => { const store = database(); const manager = new GamePackageDownloadManager({ downloadGamePackage: async () => envelope({ payloadHash: "b".repeat(64) }) }, store); await expect(manager.download("token", gameId)).rejects.toMatchObject({ code: "PACKAGE_HASH_MISMATCH" }); expect(store.getCurrentGamePackageStatus(gameId).availableOffline).toBe(false); store.close(); });
  it("rejects a malformed envelope", () => { expect(() => parseGamePackageEnvelope({ gameId })).toThrow(GamePackageFlowError); });
  it("rejects unsupported schema", () => { expect(() => parseGamePackageEnvelope(envelope({ packageSchemaVersion: 2 }))).toThrow(GamePackageFlowError); });
  it("rejects requested and envelope Game mismatch", () => { expect(() => verifyDownloadedGamePackage("game-2", envelope())).toThrow(GamePackageFlowError); });
  it("rejects payload and envelope Game mismatch", () => { const other = payloadJson.replace('"id":"game-1"', '"id":"game-2"'); const hash = createHash("sha256").update(Buffer.from(other, "utf8")).digest("hex"); expect(() => verifyDownloadedGamePackage(gameId, envelope({ payloadJson: other, payloadHash: hash }))).toThrow(GamePackageFlowError); });
  it.each([[true, true], [false, false]])("rejects incoherent result policy %s/%s", (tieAllowed, winnerRequired) => { const payload = JSON.parse(payloadJson); payload.settings.tie_allowed = tieAllowed; payload.settings.winner_required = winnerRequired; const invalidPayload = JSON.stringify(payload); const invalidHash = createHash("sha256").update(Buffer.from(invalidPayload, "utf8")).digest("hex"); expect(() => verifyDownloadedGamePackage(gameId, envelope({ payloadJson: invalidPayload, payloadHash: invalidHash }))).toThrow(GamePackageFlowError); });
  it("saves a successfully verified Package", async () => { const store = database(); const result = await new GamePackageDownloadManager({ downloadGamePackage: async () => envelope() }, store).download("token", gameId); expect(result.outcome).toBe("stored"); expect(result.status.availableOffline).toBe(true); store.close(); });
  it("is idempotent for the same Package", async () => { const store = database(); const manager = new GamePackageDownloadManager({ downloadGamePackage: async () => envelope() }, store); await manager.download("token", gameId); expect((await manager.download("token", gameId)).outcome).toBe("unchanged"); store.close(); });
  it("uses accepted store semantics for a newer version", async () => { const store = database(); let version = 1; const manager = new GamePackageDownloadManager({ downloadGamePackage: async () => { const versionPayload = version === 1 ? payloadJson : `${payloadJson} `; return envelope({ packageId: `package-v${version}`, packageVersion: version, payloadJson: versionPayload, payloadHash: createHash("sha256").update(Buffer.from(versionPayload, "utf8")).digest("hex") }); } }, store); await manager.download("token", gameId); version = 2; const current = await manager.download("token", gameId); expect(current.status.currentVersion).toBe(2); store.close(); });
  it("preserves the previous Package on network failure", async () => { const store = database(); store.storeVerifiedGamePackage(verifyDownloadedGamePackage(gameId, envelope())); const manager = new GamePackageDownloadManager({ downloadGamePackage: async () => { throw new AuthFlowError("NETWORK_UNAVAILABLE"); } }, store); await expect(manager.download("token", gameId)).rejects.toMatchObject({ code: "NETWORK_UNAVAILABLE" }); expect(store.getCurrentGamePackageStatus(gameId).currentVersion).toBe(1); store.close(); });
  it("preserves SESSION_INVALID", async () => { const store = database(); const manager = new GamePackageDownloadManager({ downloadGamePackage: async () => { throw new AuthFlowError("SESSION_INVALID"); } }, store); await expect(manager.download("token", gameId)).rejects.toMatchObject({ code: "SESSION_INVALID" }); store.close(); });
  it("returns status without payload or hash exposure", async () => { const store = database(); const result = await new GamePackageDownloadManager({ downloadGamePackage: async () => envelope() }, store).download("token", gameId); const serialized = JSON.stringify(result.status); expect(serialized).not.toContain("payload"); expect(serialized).not.toContain("hash"); expect(serialized).not.toContain("packageId"); store.close(); });
  it("prevents concurrent duplicate downloads for one Game", async () => { const store = database(); let release; const wait = new Promise((resolve) => { release = resolve; }); const manager = new GamePackageDownloadManager({ downloadGamePackage: async () => { await wait; return envelope(); } }, store); const first = manager.download("token", gameId); await expect(manager.download("token", gameId)).rejects.toMatchObject({ code: "PACKAGE_CONFLICT" }); release(); await first; store.close(); });
});
