import fs from "node:fs"; import os from "node:os"; import path from "node:path"; import { afterEach, describe, expect, it, vi } from "vitest";
import contracts from "../../dist-electron/auth/auth-contracts.cjs"; import clientModule from "../../dist-electron/auth/platform-auth-client.cjs"; import coordinatorModule from "../../dist-electron/auth/auth-coordinator.cjs"; import storeModule from "../../dist-electron/auth/secure-session-store.cjs";
const { AuthFlowError } = contracts; const { PlatformAuthClient } = clientModule; const { AuthCoordinator } = coordinatorModule; const { SecureSessionStore } = storeModule; const token = "A".repeat(43); const roots = [];
const context = { scorerId: "scorer-1", username: "test", organizationId: "organization-a", organizationName: "Organization A", sessionId: "session-1", deviceId: "device-12345678", expiresAt: "2099-08-26T00:00:00.000Z" };
const game = { gameId: "game-1", packageId: "package-1", packageVersion: 2, homeTeam: { id: "home-1", name: "Home" }, awayTeam: { id: "away-1", name: "Away" }, competition: { id: "competition-1", name: "League" }, seasonName: "2026-27", phaseName: "Regular", roundLabel: "Round 1", scheduledDate: "2026-08-26", scheduledTime: "20:00", scheduledAt: null, venue: null, publishedAt: "2026-08-24T20:00:00.000Z" };
function response(status, payload) { return new Response(JSON.stringify(payload), { status, headers: { "content-type": "application/json" } }); }
function cipher() { return { isEncryptionAvailable: () => true, encryptString: (value) => Buffer.from(`encrypted:${value}`), decryptString: (value) => value.toString("utf8").replace(/^encrypted:/, "") }; }
function store() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "komocontrol-games-")); roots.push(root); return new SecureSessionStore(path.join(root, "secure", "session.bin"), cipher()); }
function client(overrides = {}) { return { login: vi.fn(async () => ({ token, ...context })), getSession: vi.fn(async () => context), logout: vi.fn(async () => undefined), listGames: vi.fn(async () => [game]), ...overrides }; }
afterEach(() => { vi.restoreAllMocks(); for (const root of roots.splice(0)) fs.rmSync(root, { recursive: true, force: true }); });
describe("KomoControl desktop Game discovery", () => {
    it("lists and validates safe available Games", async () => { const fetcher = vi.fn(async () => response(200, { data: [game] })); const api = new PlatformAuthClient("http://localhost:3000", 100, fetcher); expect(await api.listGames(token)).toEqual([game]); expect(fetcher.mock.calls[0][0]).toBe("http://localhost:3000/api/komocontrol/v1/games"); expect(fetcher.mock.calls[0][1].headers.authorization).toBe(`Bearer ${token}`); });
    it("accepts an empty discovery list", async () => { const api = new PlatformAuthClient("http://localhost:3000", 100, async () => response(200, { data: [] })); expect(await api.listGames(token)).toEqual([]); });
    it("rejects malformed discovery responses", async () => { const api = new PlatformAuthClient("http://localhost:3000", 100, async () => response(200, { data: [{ ...game, homeTeam: null }] })); await expect(api.listGames(token)).rejects.toMatchObject({ code: "MALFORMED_RESPONSE" }); });
    it("maps network failure without exposing the token", async () => { const api = new PlatformAuthClient("http://localhost:3000", 100, async () => { throw new TypeError("offline"); }); await expect(api.listGames(token)).rejects.toMatchObject({ code: "NETWORK_UNAVAILABLE" }); });
    it("returns only the safe DTO even when the server object has extra payload", async () => { const api = new PlatformAuthClient("http://localhost:3000", 100, async () => response(200, { data: [{ ...game, token, snapshot_json: "private", players: ["private-player"] }] })); const serialized = JSON.stringify(await api.listGames(token)); expect(serialized).not.toContain(token); expect(serialized).not.toContain("snapshot_json"); expect(serialized).not.toContain("private-player"); });
    it("invalidates the local session when discovery returns SESSION_INVALID", async () => { const secureStore = store(); const api = client({ listGames: vi.fn(async () => { throw new AuthFlowError("SESSION_INVALID"); }) }); const coordinator = new AuthCoordinator(api, secureStore, "device-12345678"); await coordinator.login({ username: "test", password: "synthetic" }); const result = await coordinator.listGames(); expect(result.ok).toBe(false); expect(result.errorCode).toBe("SESSION_INVALID"); expect(result.state.kind).toBe("unauthenticated"); expect(secureStore.hasSession()).toBe(false); });
    it("preserves the secure session when discovery is temporarily offline", async () => { const secureStore = store(); const api = client({ listGames: vi.fn(async () => { throw new AuthFlowError("NETWORK_UNAVAILABLE"); }) }); const coordinator = new AuthCoordinator(api, secureStore, "device-12345678"); await coordinator.login({ username: "test", password: "synthetic" }); const result = await coordinator.listGames(); expect(result.ok).toBe(false); expect(result.errorCode).toBe("NETWORK_UNAVAILABLE"); expect(result.state.kind).toBe("authenticated"); expect(secureStore.hasSession()).toBe(true); });
});
