import { describe, expect, it } from "vitest";
import { ScorerSessionAuthority, type ScorerAuthStore, type SessionRecord } from "./komocontrol-scorer-auth-core";
import { projectAvailableGames, type PublishedGamePackageRow } from "./komocontrol-game-discovery-core";

const organizationId = "organization-a"; const token = "A".repeat(43);
const scorer = { id: "scorer-1", organizationId, organizationName: "Organization A", username: "test", normalizedUsername: "test", status: "active" as const, credentialVersion: 1 };
function snapshot(gameId: string, options: { organization?: string; date?: string; time?: string } = {}) { return JSON.stringify({ schemaVersion: 1, game: { id: gameId, organizationId: options.organization ?? organizationId, competitionId: "competition-1", competitionName: "League", seasonName: "2026-27", phaseName: "Regular", roundLabel: "Round 1", scheduledDate: options.date ?? "2026-08-26", scheduledTime: options.time ?? "20:00", scheduledAt: null, venue: "Court A" }, settings: { secretRules: true }, teams: [{ side: "HOME", id: `home-${gameId}`, name: "Home", players: [{ id: "private-player" }] }, { side: "AWAY", id: `away-${gameId}`, name: "Away", players: [{ id: "private-player" }] }] }); }
function row(gameId: string, overrides: Partial<PublishedGamePackageRow> = {}): PublishedGamePackageRow { return { id: `package-${gameId}-v1`, game_id: gameId, organization_id: organizationId, package_version: 1, status: "published", snapshot_json: snapshot(gameId), published_at: "2026-08-24T20:00:00.000Z", ...overrides }; }
function session(overrides: Partial<SessionRecord> = {}): SessionRecord { return { id: "session-1", scorerId: scorer.id, tokenHash: "hash", credentialVersion: 1, deviceId: "device-1", createdAt: "2026-08-25T10:00:00.000Z", expiresAt: "2026-08-25T14:00:00.000Z", revokedAt: null, scorer, ...overrides }; }
function authority(value: SessionRecord | null) { const store: ScorerAuthStore = { findScorerByNormalizedUsername: async () => null, createSession: async () => undefined, findSessionByTokenHash: async () => value, revokeSessionByTokenHash: async () => undefined }; return new ScorerSessionAuthority(store, () => new Date("2026-08-25T12:00:00.000Z")); }

describe("KomoControl scorer Game discovery", () => {
  it("rejects unauthenticated discovery through the canonical resolver", async () => { await expect(authority(null).resolve(null)).rejects.toMatchObject({ code: "AUTH_REQUIRED" }); });
  it("rejects revoked and expired sessions through the canonical resolver", async () => { await expect(authority(session({ revokedAt: "2026-08-25T11:00:00.000Z" })).resolve(`Bearer ${token}`)).rejects.toMatchObject({ code: "SESSION_INVALID" }); await expect(authority(session({ expiresAt: "2026-08-25T11:00:00.000Z" })).resolve(`Bearer ${token}`)).rejects.toMatchObject({ code: "SESSION_INVALID" }); });
  it("isolates Organizations", () => { expect(projectAvailableGames([row("game-a"), row("game-b", { organization_id: "organization-b", snapshot_json: snapshot("game-b", { organization: "organization-b" }) })], organizationId).map((game) => game.gameId)).toEqual(["game-a"]); });
  it("excludes unpublished and superseded Packages", () => { expect(projectAvailableGames([row("published"), row("superseded", { status: "superseded" }), row("revoked", { status: "revoked" })], organizationId).map((game) => game.gameId)).toEqual(["published"]); });
  it("returns the current published version once", () => { const games = projectAvailableGames([row("series", { status: "superseded" }), row("series", { id: "package-series-v2", package_version: 2 })], organizationId); expect(games).toHaveLength(1); expect(games[0].packageVersion).toBe(2); });
  it("does not project payload, roster, settings or hash data", () => { const serialized = JSON.stringify(projectAvailableGames([row("safe")], organizationId)); expect(serialized).not.toContain("private-player"); expect(serialized).not.toContain("secretRules"); expect(serialized).not.toContain("snapshot_json"); expect(serialized).not.toContain("snapshot_hash"); });
  it("sorts deterministically by schedule and Game ID", () => { const games = projectAvailableGames([row("game-c", { snapshot_json: snapshot("game-c", { date: "2026-08-27", time: "18:00" }) }), row("game-b", { snapshot_json: snapshot("game-b", { date: "2026-08-26", time: "19:00" }) }), row("game-a", { snapshot_json: snapshot("game-a", { date: "2026-08-26", time: "19:00" }) })], organizationId); expect(games.map((game) => game.gameId)).toEqual(["game-a", "game-b", "game-c"]); });
  it("returns an empty list when no current published Package exists", () => { expect(projectAvailableGames([], organizationId)).toEqual([]); });
});
