import { beforeEach, describe, expect, it, vi } from "vitest";

const reports = vi.hoisted(() => ({ read: vi.fn() }));
vi.mock("server-only", () => ({}));
vi.mock("@/services/platform-match-report.service", () => ({ readAuthoritativeCompetitionStatisticalGamesWithDb: reports.read }));

import { readPublicCompetitionStatisticsForOrganizationWithDb } from "./public-competition-statistics.service";

const line = (points, efficiency) => ({ points, twoPointMade: points / 2, twoPointAttempts: points / 2, threePointMade: 0, threePointAttempts: 0, freeThrowMade: 0, freeThrowAttempts: 0, offensiveRebounds: 0, defensiveRebounds: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0, fouls: 0, efficiency });
const game = (prefix, playerName, points, efficiency) => ({ gameId: `game_${prefix}`, scheduledDate: "2026-09-04", scheduledTime: "18:00", homeTeamId: `team_${prefix}`, homeTeamName: `${prefix} team`, awayTeamId: `opponent_${prefix}`, awayTeamName: `${prefix} opponent`, homeScore: points, awayScore: 0, homePlayers: [{ canonicalPlayerId: `player_${prefix}`, displayName: playerName, shirtNumber: "4", statistics: line(points, efficiency) }], awayPlayers: [] });

function database() {
  const calls = [];
  return { calls, binding: { prepare(query) { let values = []; const statement = { bind(...next) { values = next; calls.push({ query, values }); return statement; }, async first() { return null; }, async run() { return {}; }, async all() { if (query.includes("FROM league_competitions")) { const prefix = values[0] === "organization_runbasket" ? "runbasket" : "komobasket"; return { results: [{ season_id: `season_${prefix}`, season_name: "2026-27", season_slug: "2026-27", starts_on: "2026-08-01", competition_id: `competition_${prefix}`, competition_name: `${prefix} competition`, competition_slug: `${prefix}-competition` }] }; } if (query.includes("FROM league_games") && !query.includes("league_matchday_mvp_selections")) return { results: [{ game_id: values[0].replace("competition_", "game_"), round_number: 1, round_label: "1η Αγωνιστική" }] }; if (query.includes("FROM league_matchday_mvp_selections")) { const prefix = values[0] === "organization_runbasket" ? "runbasket" : "komobasket"; return { results: [{ id: `mvp_${prefix}`, organization_id: `organization_${prefix}`, competition_id: `competition_${prefix}`, phase_id: `phase_${prefix}`, round_number: 1, game_id: `game_${prefix}`, player_id: `player_${prefix}`, created_at: "2026-09-24T10:00:00Z", updated_at: "2026-09-24T10:00:00Z" }] }; } return { results: [] }; } }; return statement; }, async batch() { return []; } } };
}

describe("public competition statistics organization isolation", () => {
  beforeEach(() => reports.read.mockImplementation(async (_db, competitionId, organizationId) => organizationId === "organization_runbasket" ? [game("runbasket", "RUNBASKET MVP", 20, 20)] : [game("komobasket", "KOMOBASKET MVP", 50, 50)]));
  it("keeps a higher KomoBasket fixture out of RunBasket MVP", async () => { const fixture = database(); const result = await readPublicCompetitionStatisticsForOrganizationWithDb(fixture.binding, "organization_runbasket"); expect(result.competitions).toEqual([{ slug: "runbasket-competition", name: "runbasket competition" }]); expect(result.statistics?.leaders.points?.displayName).toBe("RUNBASKET MVP"); expect(result.statistics?.matchdays[0]?.mvp?.player.displayName).toBe("RUNBASKET MVP"); expect(JSON.stringify(result)).not.toContain("KOMOBASKET MVP"); expect(reports.read).toHaveBeenCalledWith(fixture.binding, "competition_runbasket", "organization_runbasket"); });
  it("keeps RunBasket out of the central organization result", async () => { const fixture = database(); const result = await readPublicCompetitionStatisticsForOrganizationWithDb(fixture.binding, "organization_komobasket"); expect(result.statistics?.leaders.points?.displayName).toBe("KOMOBASKET MVP"); expect(JSON.stringify(result)).not.toContain("RUNBASKET MVP"); });
  it("sanitizes cross-organization competition query injection", async () => { const fixture = database(); const result = await readPublicCompetitionStatisticsForOrganizationWithDb(fixture.binding, "organization_runbasket", { competitionSlug: "komobasket-competition" }); expect(result.selectedCompetition?.slug).toBe("runbasket-competition"); expect(result.competitions).not.toContainEqual({ slug: "komobasket-competition", name: "komobasket competition" }); });
});
