"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

import { PUBLIC_LEADER_CATEGORIES, publicLeaderValue, type PublicCompetitionStatisticsPlayer, type PublicLeaderCategory } from "@/lib/public-competition-statistics";
import type { PublicCompetitionStatisticsPageData } from "@/services/public-competition-statistics.service";

const CATEGORY_LABELS: Record<PublicLeaderCategory, string> = { points: "Πόντοι", threePointers: "3PT", twoPointers: "2PT", freeThrows: "FT", rebounds: "REB", offensiveRebounds: "OREB", defensiveRebounds: "DREB", assists: "AST", steals: "STL", blocks: "BLK", efficiency: "EFF" };

function rankingValue(player: PublicCompetitionStatisticsPlayer, category: PublicLeaderCategory) {
  if (category === "threePointers") return `${player.statistics.threePointMade}/${player.statistics.threePointAttempts}`;
  if (category === "twoPointers") return `${player.statistics.twoPointMade}/${player.statistics.twoPointAttempts}`;
  if (category === "freeThrows") return `${player.statistics.freeThrowMade}/${player.statistics.freeThrowAttempts}`;
  return `${publicLeaderValue(player, category)} ${CATEGORY_LABELS[category]}`;
}

function LeaderCard({ title, player, category }: { title: string; player: PublicCompetitionStatisticsPlayer | null; category: PublicLeaderCategory }) {
  return <article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-orange-700">{title}</p>{player ? <><h3 className="mt-3 text-xl font-black text-zinc-950">{player.displayName}</h3><p className="mt-1 font-bold text-zinc-600">{player.teamName} · ΑΓ. {player.gamesPlayed}</p><strong className="mt-5 block text-3xl font-black tabular-nums text-zinc-950">{rankingValue(player, category)}</strong></> : <p className="mt-4 font-bold text-zinc-500">Δεν υπάρχουν δεδομένα.</p>}</article>;
}

export default function PublicCompetitionStatisticsView({ data, basePath = "/stats" }: { data: PublicCompetitionStatisticsPageData; basePath?: string }) {
  const router = useRouter();
  const [category, setCategory] = useState<PublicLeaderCategory>("points");
  const [matchdayId, setMatchdayId] = useState(data.statistics?.matchdays[0]?.id ?? "");
  const statistics = data.statistics;
  const matchday = statistics?.matchdays.find((item) => item.id === matchdayId) ?? statistics?.matchdays[0] ?? null;
  const navigate = (season: string, competition?: string) => { const params = new URLSearchParams({ season }); if (competition) params.set("competition", competition); router.push(`${basePath}?${params}`); };
  return <div className="mt-8 space-y-8">
    <section className="grid gap-4 rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm sm:grid-cols-2 sm:p-6">
      <label><span className="mb-2 block text-xs font-black uppercase tracking-[0.16em] text-zinc-600">Σεζόν</span><select value={data.selectedSeason?.slug ?? ""} onChange={(event) => navigate(event.target.value)} className="min-h-11 w-full rounded-xl border border-zinc-300 bg-white px-4 py-2.5 font-black">{data.seasons.map((season) => <option key={season.slug} value={season.slug}>{season.name}</option>)}</select></label>
      <label><span className="mb-2 block text-xs font-black uppercase tracking-[0.16em] text-zinc-600">Διοργάνωση</span><select value={data.selectedCompetition?.slug ?? ""} onChange={(event) => navigate(data.selectedSeason?.slug ?? "", event.target.value)} className="min-h-11 w-full rounded-xl border border-zinc-300 bg-white px-4 py-2.5 font-black">{data.competitions.map((competition) => <option key={competition.slug} value={competition.slug}>{competition.name}</option>)}</select></label>
    </section>
    {!statistics || statistics.gamesIncluded === 0 ? <section className="rounded-3xl border border-zinc-200 bg-white p-8 text-center font-bold text-zinc-600">Δεν υπάρχουν διαθέσιμα authoritative στατιστικά για τη συγκεκριμένη διοργάνωση.</section> : <>
      <section><p className="text-xs font-black uppercase tracking-[0.18em] text-orange-700">Σύνολο διοργάνωσης · {statistics.gamesIncluded} αγώνες</p><h2 className="mt-2 text-3xl font-black text-zinc-950">ΚΟΡΥΦΑΙΟΙ</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><LeaderCard title="ΠΡΩΤΟΣ ΣΚΟΡΕΡ" player={statistics.leaders.points} category="points" /><LeaderCard title="3PT LEADER" player={statistics.leaders.threePointers} category="threePointers" /><LeaderCard title="REB LEADER" player={statistics.leaders.rebounds} category="rebounds" /><LeaderCard title="AST LEADER" player={statistics.leaders.assists} category="assists" /><LeaderCard title="EFF LEADER" player={statistics.leaders.efficiency} category="efficiency" /></div></section>
      <section className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-orange-700">Top 20</p><h2 className="mt-2 text-3xl font-black">LEADERS</h2></div><label><span className="mb-2 block text-xs font-black uppercase tracking-wide text-zinc-600">Κατηγορία</span><select value={category} onChange={(event) => setCategory(event.target.value as PublicLeaderCategory)} className="min-h-11 w-full rounded-xl border border-zinc-300 px-4 py-2.5 font-black sm:w-64">{PUBLIC_LEADER_CATEGORIES.map((item) => <option key={item} value={item}>{CATEGORY_LABELS[item]}</option>)}</select></label></div><div className="mt-5 overflow-x-auto rounded-2xl border border-zinc-200" tabIndex={0} aria-label={`Κατάταξη ${CATEGORY_LABELS[category]}`}><table className="w-full min-w-[680px]"><thead><tr className="bg-zinc-950 text-xs font-black text-zinc-300"><th className="sticky left-0 z-20 w-14 bg-zinc-950 px-3 py-3">#</th><th className="sticky left-14 z-20 min-w-56 bg-zinc-950 px-3 py-3 text-left">ΠΑΙΚΤΗΣ</th><th className="px-3 py-3 text-left">ΟΜΑΔΑ</th><th className="px-3 py-3">ΑΓ.</th><th className="px-3 py-3">ΕΠΙΔΟΣΗ</th></tr></thead><tbody>{statistics.rankings[category].map((player, index) => <tr key={`${player.teamName}:${player.displayName}:${index}`} className="border-t border-zinc-200 bg-white text-sm odd:bg-zinc-50/70"><td className="sticky left-0 z-10 bg-inherit px-3 py-3 text-center font-black text-orange-700">{index + 1}</td><td className="sticky left-14 z-10 bg-inherit px-3 py-3 font-black">{player.displayName}</td><td className="px-3 py-3 font-bold text-zinc-600">{player.teamName}</td><td className="px-3 py-3 text-center font-bold">{player.gamesPlayed}</td><td className="px-3 py-3 text-center font-black tabular-nums">{rankingValue(player, category)}</td></tr>)}</tbody></table></div></section>
      <section className="rounded-3xl bg-zinc-950 p-5 text-white shadow-xl sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black tracking-[0.18em] text-orange-400">ΑΝΑ ΑΓΩΝΙΣΤΙΚΗ</p><h2 className="mt-2 text-3xl font-black">TOP PERFORMANCE</h2></div>{statistics.matchdays.length ? <label><span className="mb-2 block text-xs font-black uppercase tracking-wide text-zinc-400">Αγωνιστική</span><select value={matchday?.id ?? ""} onChange={(event) => setMatchdayId(event.target.value)} className="min-h-11 w-full rounded-xl border border-zinc-600 bg-zinc-900 px-4 py-2.5 font-black sm:w-64">{statistics.matchdays.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label> : null}</div>{matchday?.incomplete ? <p className="mt-5 rounded-2xl border border-amber-500/40 bg-amber-500/10 p-5 font-bold text-amber-100">Το Top Performance θα ανακοινωθεί μετά την ολοκλήρωση όλων των αγώνων της αγωνιστικής.</p> : matchday?.topPerformance ? <article className="mt-5 rounded-2xl bg-white p-5 text-zinc-950 sm:p-6"><p className="text-sm font-black text-orange-700">{matchday.label}</p><h3 className="mt-2 text-2xl font-black">#{matchday.topPerformance.player.shirtNumber} {matchday.topPerformance.player.displayName}</h3><p className="mt-1 font-bold text-zinc-600">{matchday.topPerformance.teamName}</p><div className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-6">{(["points", "rebounds", "assists", "steals", "blocks", "efficiency"] as const).map((key) => <div key={key} className="rounded-xl bg-zinc-100 p-3 text-center"><span className="block text-xs font-black uppercase text-zinc-500">{{ points: "PTS", rebounds: "REB", assists: "AST", steals: "STL", blocks: "BLK", efficiency: "EFF" }[key]}</span><strong className="mt-1 block text-xl">{matchday.topPerformance!.statistics[key]}</strong></div>)}</div><p className="mt-5 border-t border-zinc-200 pt-4 font-black">{matchday.topPerformance.teamName} {matchday.topPerformance.finalScore.team}–{matchday.topPerformance.finalScore.opponent} {matchday.topPerformance.opponentName}</p>{matchday.topPerformance.scheduledDate ? <p className="mt-1 text-sm font-bold text-zinc-500">{matchday.topPerformance.scheduledDate}</p> : null}</article> : <p className="mt-5 rounded-2xl bg-zinc-900 p-5 font-bold text-zinc-300">Δεν υπάρχουν διαθέσιμα δεδομένα για Top Performance.</p>}</section>
    </>}
  </div>;
}
