import { requireAdmin } from "@/lib/admin-auth";
import { resolveCanonicalAppUser } from "@/lib/app-user-identity";
import { platformAuthorizationErrorResponse, requireOrganizationAccess, requirePlatformSuperAdmin } from "@/lib/platform-authorization";
import { buildGamePackagePreview, createRegistryEntry, createScorer, komoControlAdminErrorResponse, listKomoControlGames, listKomoControlSettings, listRegistry, listScorers, publishGamePackage, publishGamePackages, saveGameOverride, saveKomoControlSettings, updateRegistryEntry, updateScorer } from "@/services/komocontrol-admin.service";

type Resource = "settings" | "scorers" | "referees" | "table-officials" | "games" | "game-settings";
const isResource = (value: string): value is Resource => ["settings", "scorers", "referees", "table-officials", "games", "game-settings"].includes(value);
const isRegistryResource = (value: Resource): value is "referees" | "table-officials" => value === "referees" || value === "table-officials";

async function context(request: Request, route: { params: Promise<{ resource: string }> }) {
  const authorization = await requireAdmin(request); if (authorization.response) return { response: authorization.response } as const;
  const { resource } = await route.params; if (!isResource(resource)) return { response: Response.json({ error: "Μη υποστηριζόμενος πόρος KomoControl." }, { status: 404 }) } as const;
  const organizationId = new URL(request.url).searchParams.get("organizationId")?.trim() || "";
  if (!organizationId) return { response: Response.json({ error: "Απαιτείται Οργανισμός." }, { status: 400 }) } as const;
  const user = await resolveCanonicalAppUser(authorization.identity);
  if (resource === "scorers") await requirePlatformSuperAdmin(user);
  await requireOrganizationAccess(user, organizationId, "manage");
  return { response: null, resource, organizationId, user } as const;
}
function failure(error: unknown) { return platformAuthorizationErrorResponse(error) ?? komoControlAdminErrorResponse(error) ?? Response.json({ error: error instanceof Error ? error.message : "Η ενέργεια απέτυχε." }, { status: 400 }); }
export async function GET(request: Request, route: { params: Promise<{ resource: string }> }) { try { const resolved=await context(request,route);if(resolved.response)return resolved.response;const url=new URL(request.url);if(resolved.resource==="settings")return Response.json(await listKomoControlSettings(resolved.organizationId,url.searchParams.get("competitionId")?.trim()||undefined));if(resolved.resource==="games")return Response.json({games:await listKomoControlGames(resolved.organizationId,url.searchParams.get("fromDate")?.trim()||"",url.searchParams.get("toDate")?.trim()||"",url.searchParams.get("competitionId")?.trim()||undefined)});if(resolved.resource==="game-settings")return Response.json(await buildGamePackagePreview(resolved.organizationId,url.searchParams.get("gameId")?.trim()||""));if(resolved.resource==="scorers")return Response.json({scorers:await listScorers(resolved.organizationId)});if(isRegistryResource(resolved.resource))return Response.json({entries:await listRegistry(resolved.organizationId,resolved.resource)});return Response.json({ error: "Μη υποστηριζόμενος πόρος KomoControl." }, { status: 404 }); } catch(error){return failure(error);} }
export async function POST(request: Request, route: { params: Promise<{ resource: string }> }) { try { const resolved=await context(request,route);if(resolved.response)return resolved.response;const input=await request.json() as Record<string,unknown>;if(resolved.resource==="settings")return Response.json({settings:await saveKomoControlSettings(resolved.organizationId,input)});if(resolved.resource==="game-settings")return Response.json(await saveGameOverride(resolved.organizationId,input));if(resolved.resource==="games")return Response.json(Array.isArray(input.gameIds)?await publishGamePackages(resolved.organizationId,input.gameIds,resolved.user.userId):await publishGamePackage(resolved.organizationId,String(input.gameId??""),resolved.user.userId));if(resolved.resource==="scorers")return Response.json({scorer:await createScorer(resolved.organizationId,input)},{status:201});if(isRegistryResource(resolved.resource))return Response.json({entry:await createRegistryEntry(resolved.organizationId,resolved.resource,input)},{status:201});return Response.json({ error: "Μη υποστηριζόμενος πόρος KomoControl." }, { status: 404 }); } catch(error){return failure(error);} }
export async function PATCH(request: Request, route: { params: Promise<{ resource: string }> }) { try { const resolved=await context(request,route);if(resolved.response)return resolved.response;const input=await request.json() as Record<string,unknown>;if(resolved.resource==="scorers"){await updateScorer(resolved.organizationId,input);return Response.json({ok:true});}if(resolved.resource==="settings")return Response.json({settings:await saveKomoControlSettings(resolved.organizationId,input)});if(resolved.resource==="game-settings")return Response.json(await saveGameOverride(resolved.organizationId,input));if(isRegistryResource(resolved.resource)){await updateRegistryEntry(resolved.organizationId,resolved.resource,input);return Response.json({ok:true});}return Response.json({ error: "Μη υποστηριζόμενος πόρος KomoControl." }, { status: 404 }); } catch(error){return failure(error);} }
