import { useCallback, useEffect, useState, type FormEvent } from "react";
import { PreGameConfiguration } from "./components/PreGameConfiguration";

const errorMessages: Record<KomoControlAuthErrorCode, string> = {
    AUTH_INVALID: "Λανθασμένο όνομα χρήστη ή κωδικός.", SCORER_DISABLED: "Ο λογαριασμός scorer δεν είναι ενεργός.", SESSION_INVALID: "Η σύνδεση έληξε. Συνδεθείτε ξανά.",
    NETWORK_UNAVAILABLE: "Δεν είναι δυνατή η σύνδεση με τον διακομιστή.", MALFORMED_RESPONSE: "Ο διακομιστής επέστρεψε μη έγκυρη απάντηση.",
    SECURE_STORAGE_UNAVAILABLE: "Η ασφαλής αποθήκευση των Windows δεν είναι διαθέσιμη.", LOCAL_SESSION_ERROR: "Η ασφαλής τοπική σύνδεση δεν μπόρεσε να ενημερωθεί.", CONFIGURATION_ERROR: "Η σύνδεση με το KomoPlatform δεν έχει ρυθμιστεί.",
};
const packageErrorMessages: Record<Exclude<KomoControlGamePackageErrorCode, KomoControlAuthErrorCode>, string> = { PACKAGE_UNAVAILABLE: "Το πακέτο του αγώνα δεν είναι πλέον διαθέσιμο.", PACKAGE_INVALID: "Το πακέτο του αγώνα δεν είναι έγκυρο.", PACKAGE_HASH_MISMATCH: "Η επαλήθευση του πακέτου απέτυχε.", PACKAGE_CONFLICT: "Το τοπικό πακέτο δεν μπορεί να αντικατασταθεί με ασφάλεια.", PACKAGE_UNSUPPORTED: "Η έκδοση του πακέτου δεν υποστηρίζεται από αυτή την εφαρμογή." };
function operationError(code: KomoControlGamePackageErrorCode): string { return code in packageErrorMessages ? packageErrorMessages[code as keyof typeof packageErrorMessages] : errorMessages[code as KomoControlAuthErrorCode]; }
const runErrorMessages: Record<KomoControlMatchRunErrorCode, string> = { RUN_UNAVAILABLE: "Δεν βρέθηκε ενεργό τοπικό Run.", RUN_INVALID: "Το τοπικό Run δεν είναι έγκυρο.", RUN_CONFLICT: "Υπάρχει διαφορετικό ενεργό τοπικό Run για αυτόν τον αγώνα.", RUN_OWNERSHIP_CONFLICT: "Το ενεργό τοπικό Run ανήκει σε διαφορετικό scorer ή συσκευή." };
function runOperationError(code: KomoControlMatchRunErrorCode | "SESSION_INVALID"): string { return code === "SESSION_INVALID" ? errorMessages.SESSION_INVALID : runErrorMessages[code]; }
const configurationErrorMessages: Record<KomoControlPreGameConfigurationErrorCode, string> = { CONFIGURATION_UNAVAILABLE: "Δεν υπάρχει διαθέσιμη τοπική διαμόρφωση για αυτό το Run.", CONFIGURATION_INVALID: "Το draft δεν είναι έγκυρο. Ελέγξτε τις συμμετοχές και τους αριθμούς.", CONFIGURATION_CONFLICT: "Το draft άλλαξε ή το Run δεν είναι πλέον σε κατάσταση προετοιμασίας.", CONFIGURATION_OWNERSHIP_CONFLICT: "Το Run ανήκει σε διαφορετικό scorer ή συσκευή." };
function configurationOperationError(code: KomoControlPreGameConfigurationErrorCode | "SESSION_INVALID"): string { return code === "SESSION_INVALID" ? errorMessages.SESSION_INVALID : configurationErrorMessages[code]; }

function displayDate(value: string) { const [year, month, day] = value.split("-"); return `${day}/${month}/${year}`; }

function App() {
    const bridge = window.komoControl;
    const [authState, setAuthState] = useState<KomoControlAuthState | null>(null);
    const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
    const [version, setVersion] = useState("0.1.0"); const [localReady, setLocalReady] = useState(false);
    const [games, setGames] = useState<KomoControlAvailableGame[]>([]); const [gamesLoading, setGamesLoading] = useState(false); const [gamesLoaded, setGamesLoaded] = useState(false); const [gamesError, setGamesError] = useState<string | null>(null);
    const [offlineStatuses, setOfflineStatuses] = useState<Record<string, KomoControlOfflineGameStatus>>({}); const [downloadingGameId, setDownloadingGameId] = useState<string | null>(null); const [downloadErrors, setDownloadErrors] = useState<Record<string, string>>({});
    const [matchSetup, setMatchSetup] = useState<KomoControlMatchSetup | null>(null); const [openingSetupGameId, setOpeningSetupGameId] = useState<string | null>(null); const [matchSetupError, setMatchSetupError] = useState<string | null>(null);
    const [activeRun, setActiveRun] = useState<KomoControlSafeMatchRun | null>(null); const [runBusy, setRunBusy] = useState(false); const [runError, setRunError] = useState<string | null>(null);
    const [preGameConfiguration, setPreGameConfiguration] = useState<KomoControlPreGameConfiguration | null>(null); const [preGameBusy, setPreGameBusy] = useState(false); const [preGameError, setPreGameError] = useState<string | null>(null); const [preGameSavedRevision, setPreGameSavedRevision] = useState<number | null>(null);
    useEffect(() => { if (!bridge) return; void Promise.all([bridge.getAuthState(), bridge.getAppInfo(), bridge.getLocalStatus()]).then(([state, info, local]) => { setAuthState(state); setVersion(info.version); setLocalReady(local.ready); }).catch(() => setError(errorMessages.LOCAL_SESSION_ERROR)); }, [bridge]);
    const loadGames = useCallback(async () => { if (!bridge) return; setGamesLoading(true); setGamesError(null); try { const result = await bridge.listAvailableGames(); setAuthState(result.state); if (result.ok) { setGames(result.games); setGamesLoaded(true); const statuses = await Promise.all(result.games.map((game) => bridge.getOfflineGameStatus(game.gameId))); setOfflineStatuses(Object.fromEntries(statuses.map((status) => [status.gameId, status]))); } else { setGamesError(errorMessages[result.errorCode]); if (result.state.kind !== "authenticated") { setGames([]); setGamesLoaded(false); setOfflineStatuses({}); } } } catch { setGamesError(errorMessages.NETWORK_UNAVAILABLE); } finally { setGamesLoading(false); } }, [bridge]);
    useEffect(() => { if (authState?.kind === "authenticated") void loadGames(); else { setGames([]); setGamesLoaded(false); setGamesError(null); setMatchSetup(null); setMatchSetupError(null); setActiveRun(null); setRunError(null); setPreGameConfiguration(null); setPreGameError(null); setPreGameSavedRevision(null); } }, [authState?.kind, loadGames]);
    async function submitLogin(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!bridge || busy) return; setBusy(true); setError(null); const submittedPassword = password; setPassword(""); try { const result = await bridge.login({ username, password: submittedPassword }); setAuthState(result.state); if (!result.ok) setError(errorMessages[result.errorCode]); } catch { setError(errorMessages.NETWORK_UNAVAILABLE); } finally { setBusy(false); } }
    async function retrySession() { if (!bridge || busy) return; setBusy(true); setError(null); try { const result = await bridge.retrySession(); setAuthState(result.state); if (!result.ok) setError(errorMessages[result.errorCode]); } catch { setError(errorMessages.NETWORK_UNAVAILABLE); } finally { setBusy(false); } }
    async function logout() { if (!bridge || busy) return; setBusy(true); setError(null); try { const result = await bridge.logout(); setAuthState(result.state); if (!result.ok) setError(errorMessages[result.errorCode]); } catch { setError(errorMessages.LOCAL_SESSION_ERROR); } finally { setBusy(false); } }
    async function downloadPackage(gameId: string) { if (!bridge || downloadingGameId) return; setDownloadingGameId(gameId); setDownloadErrors((current) => { const next = { ...current }; delete next[gameId]; return next; }); try { const result = await bridge.downloadGamePackage(gameId); setAuthState(result.state); if (result.ok) setOfflineStatuses((current) => ({ ...current, [gameId]: result.status })); else setDownloadErrors((current) => ({ ...current, [gameId]: operationError(result.errorCode) })); } catch { setDownloadErrors((current) => ({ ...current, [gameId]: errorMessages.NETWORK_UNAVAILABLE })); } finally { setDownloadingGameId(null); } }
    async function openMatchSetup(gameId: string) { if (!bridge || openingSetupGameId) return; setOpeningSetupGameId(gameId); setMatchSetupError(null); setRunError(null); setActiveRun(null); setPreGameConfiguration(null); setPreGameError(null); setPreGameSavedRevision(null); try { const result = await bridge.getMatchSetup(gameId); setAuthState(result.state); if (!result.ok) { setMatchSetupError(operationError(result.errorCode)); return; } setMatchSetup(result.setup); const runResult = await bridge.getActiveGameRun(gameId); setAuthState(runResult.state); if (runResult.ok) setActiveRun(runResult.run); else setRunError(runOperationError(runResult.errorCode)); } catch { setMatchSetupError("Δεν ήταν δυνατή η ασφαλής ανάγνωση του τοπικού πακέτου."); } finally { setOpeningSetupGameId(null); } }
    async function createOrOpenRun() { if (!bridge || !matchSetup || runBusy) return; setRunBusy(true); setRunError(null); try { const result = await bridge.createOrOpenGameRun(matchSetup.gameId); setAuthState(result.state); if (result.ok) setActiveRun(result.run); else setRunError(runOperationError(result.errorCode)); } catch { setRunError("Δεν ήταν δυνατή η ασφαλής δημιουργία του τοπικού Run."); } finally { setRunBusy(false); } }
    async function openPreGameConfiguration() { if (!bridge || !matchSetup || !activeRun || preGameBusy) return; setPreGameBusy(true); setPreGameError(null); setPreGameSavedRevision(null); try { const result = await bridge.getOrCreatePreGameConfiguration(matchSetup.gameId); setAuthState(result.state); if (result.ok) setPreGameConfiguration(result.configuration); else setPreGameError(configurationOperationError(result.errorCode)); } catch { setPreGameError("Δεν ήταν δυνατό να ανοίξει το τοπικό draft."); } finally { setPreGameBusy(false); } }
    async function savePreGameConfiguration(input: KomoControlPreGameConfigurationSaveDraftInput) { if (!bridge || preGameBusy) return; setPreGameBusy(true); setPreGameError(null); setPreGameSavedRevision(null); try { const result = await bridge.savePreGameConfigurationDraft(input); setAuthState(result.state); if (result.ok) { setPreGameConfiguration(result.configuration); setPreGameSavedRevision(result.configuration.revision); } else setPreGameError(configurationOperationError(result.errorCode)); } catch { setPreGameError("Δεν ήταν δυνατή η ασφαλής αποθήκευση του draft."); } finally { setPreGameBusy(false); } }
    if (!bridge) return <main className="auth-shell"><section className="auth-card"><h1>KomoControl</h1><p>Η ασφαλής desktop σύνδεση δεν είναι διαθέσιμη.</p></section></main>;
    if (!authState) return <main className="auth-shell"><section className="auth-card loading-card"><span className="basketball-mark">K</span><p>Έλεγχος ασφαλούς σύνδεσης…</p></section></main>;
    const footer = <footer><span>v{version} · Creator: D. Seretidis</span><span>{localReady ? "Local DB έτοιμη" : "Local DB μη διαθέσιμη"}</span><span>Συσκευή · {authState.deviceIdSuffix}</span></footer>;
    if (authState.kind === "authenticated" && matchSetup && preGameConfiguration) return <PreGameConfiguration configuration={preGameConfiguration} busy={preGameBusy} error={preGameError} savedRevision={preGameSavedRevision} footer={footer} onBack={() => { setPreGameConfiguration(null); setPreGameError(null); setPreGameSavedRevision(null); }} onDraftEdited={() => setPreGameSavedRevision(null)} onSave={savePreGameConfiguration} />;
    if (authState.kind === "authenticated" && matchSetup) {
        const renderTeam = (team: KomoControlMatchSetupTeam) => <section className="setup-team" key={team.side}><div className="setup-team-heading"><div className="setup-team-mark">{team.teamName.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase()}</div><div><span>{team.side}</span><h2>{team.teamName}</h2></div></div><h3>Διαθέσιμο ρόστερ · {team.players.length}</h3><div className="setup-roster">{team.players.map((player) => <div className="setup-person" key={player.playerId}><span className="setup-shirt">{player.shirtNumber ?? "—"}</span><span>{player.displayName}</span></div>)}</div>{team.staff.length > 0 ? <><h3>Πάγκος / Staff</h3><div className="setup-roster">{team.staff.map((member) => <div className="setup-person" key={member.staffId}><span>{member.displayName}</span><small>{member.roleLabel ?? member.role}</small></div>)}</div></> : null}</section>;
        return <main className="home-shell"><section className="home-card setup-card"><div className="setup-toolbar"><button className="secondary-button" type="button" onClick={() => { setMatchSetup(null); setActiveRun(null); setRunError(null); setPreGameConfiguration(null); setPreGameError(null); }}>← Οι αγώνες μου</button><span className="offline-ready">Τοπικό πακέτο · v{matchSetup.packageVersion}</span></div><header className="setup-context"><span className="eyebrow">ΠΡΟΕΤΟΙΜΑΣΙΑ ΑΓΩΝΑ</span><h1>{matchSetup.home.teamName} — {matchSetup.away.teamName}</h1><p>{matchSetup.competitionName} · {matchSetup.seasonName}{matchSetup.roundLabel ? ` · ${matchSetup.roundLabel}` : ""}</p><p>{matchSetup.scheduledDate ? displayDate(matchSetup.scheduledDate) : "Ημερομηνία —"} · {matchSetup.scheduledTime ?? "Ώρα —"}{matchSetup.venue ? ` · ${matchSetup.venue}` : ""}</p></header><div className="setup-teams">{renderTeam(matchSetup.home)}{renderTeam(matchSetup.away)}</div><section className="setup-rules"><div><span>Λειτουργία</span><strong>{matchSetup.settings.gameMode === "FULL" ? "Πλήρη στατιστικά" : "Απλό φύλλο αγώνα"}</strong></div><div><span>Περίοδοι</span><strong>{matchSetup.settings.regulationPeriods} × {Math.floor(matchSetup.settings.regulationPeriodSeconds / 60)}′</strong></div><div><span>Παράταση</span><strong>{Math.floor(matchSetup.settings.overtimeSeconds / 60)}′</strong></div><div><span>Αρχική πεντάδα</span><strong>{matchSetup.settings.startingPlayers}</strong></div><div><span>Ρόστερ</span><strong>{matchSetup.settings.minPlayers}–{matchSetup.settings.maxPlayers}</strong></div><div><span>Ισοπαλία</span><strong>{matchSetup.settings.tieAllowed ? "Επιτρέπεται" : "Δεν επιτρέπεται"}</strong></div></section><section className={`run-foundation ${activeRun ? "ready" : ""}`}><div><span className="eyebrow">ΤΟΠΙΚΟ GAME RUN</span><h2>{activeRun ? "Το Run είναι ασφαλώς αποθηκευμένο" : "Δημιουργία durable Run"}</h2><p>{activeRun ? `Run · ${activeRun.runId.slice(-8)} · Πακέτο v${activeRun.packageVersion}` : "Θα κλειδώσει το επαληθευμένο πακέτο, τον scorer και αυτή τη συσκευή."}</p><strong>Η αγωνιστική καταγραφή δεν έχει ξεκινήσει.</strong></div>{activeRun ? <div className="run-actions"><span className="offline-ready">ACTIVE · PRE-ENGINE</span><button className="primary-button" type="button" disabled={preGameBusy} onClick={() => void openPreGameConfiguration()}>{preGameBusy ? "Άνοιγμα…" : "Συμμετοχές και αριθμοί"}</button></div> : <button className="primary-button" type="button" disabled={runBusy} onClick={() => void createOrOpenRun()}>{runBusy ? "Δημιουργία…" : "Δημιουργία τοπικού Run"}</button>}</section>{runError ? <p className="form-error" role="alert">{runError}</p> : null}{preGameError ? <p className="form-error" role="alert">{preGameError}</p> : null}<button className="secondary-button logout-button" type="button" disabled={busy} onClick={() => void logout()}>{busy ? "Αποσύνδεση…" : "Αποσύνδεση"}</button>{footer}</section></main>;
    }
    if (authState.kind === "authenticated") return <main className="home-shell"><section className="home-card"><header className="brand-row"><div className="basketball-mark">K</div><div><span className="eyebrow">KOMOBASKET OFFICIAL SCORER</span><h1>KomoControl</h1></div></header><div className="connection-pill"><span />Online · Επιβεβαιωμένη σύνδεση</div><div className="identity-panel"><span className="eyebrow">ΣΥΝΔΕΔΕΜΕΝΟΣ ΩΣ</span><strong>{authState.context.username}</strong><p>{authState.context.organizationName}</p></div><section className="games-section"><div className="section-heading"><div><span className="eyebrow">ΔΙΑΘΕΣΙΜΑ ΣΤΟ KOMOCONTROL</span><h2>Οι αγώνες μου</h2></div><button className="refresh-button" type="button" disabled={gamesLoading} onClick={() => void loadGames()}>{gamesLoading ? "Ανανέωση…" : "Ανανέωση"}</button></div>{gamesLoading && !gamesLoaded ? <p className="games-state">Φόρτωση αγώνων…</p> : null}{gamesError ? <div className="games-error" role="alert"><p>{gamesError}</p><button className="secondary-button" type="button" disabled={gamesLoading} onClick={() => void loadGames()}>Νέα προσπάθεια</button></div> : null}{matchSetupError ? <p className="form-error" role="alert">{matchSetupError}</p> : null}{!gamesLoading && !gamesError && gamesLoaded && games.length === 0 ? <p className="games-state">Δεν υπάρχουν διαθέσιμοι αγώνες.</p> : null}{games.length > 0 ? <div className="games-list">{games.map((game) => <article className="game-card" key={game.gameId}><div className="game-date"><strong>{displayDate(game.scheduledDate)}</strong><span>{game.scheduledTime}</span></div><div className="game-main"><h3>{game.homeTeam.name} <span>—</span> {game.awayTeam.name}</h3><p>{game.competition.name}{game.roundLabel ? ` · ${game.roundLabel}` : ""}</p>{game.venue ? <p className="game-venue">{game.venue}</p> : null}{downloadErrors[game.gameId] ? <p className="game-download-error" role="alert">{downloadErrors[game.gameId]}</p> : null}</div><div className="game-offline-action">{offlineStatuses[game.gameId]?.availableOffline ? <div className="offline-actions"><span className="offline-ready">Διαθέσιμο offline · v{offlineStatuses[game.gameId].currentVersion}</span><button className="secondary-button" type="button" disabled={openingSetupGameId !== null} onClick={() => void openMatchSetup(game.gameId)}>{openingSetupGameId === game.gameId ? "Έλεγχος πακέτου…" : "Προετοιμασία αγώνα"}</button></div> : <button type="button" disabled={downloadingGameId !== null} onClick={() => void downloadPackage(game.gameId)}>{downloadingGameId === game.gameId ? "Επαλήθευση…" : "Λήψη για offline"}</button>}</div></article>)}</div> : null}</section>{error && <p className="form-error" role="alert">{error}</p>}<button className="secondary-button logout-button" type="button" disabled={busy} onClick={() => void logout()}>{busy ? "Αποσύνδεση…" : "Αποσύνδεση"}</button>{footer}</section></main>;
    if (authState.kind === "validation-unavailable") return <main className="auth-shell"><section className="auth-card"><header className="brand-row"><div className="basketball-mark">K</div><div><span className="eyebrow">OFFLINE</span><h1>Απαιτείται επιβεβαίωση</h1></div></header><p className="intro">Η κρυπτογραφημένη σύνδεση διατηρήθηκε, αλλά το KomoPlatform δεν είναι διαθέσιμο. Δεν έχει δοθεί αγωνιστική εξουσιοδότηση.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="button-row"><button className="primary-button" type="button" disabled={busy} onClick={() => void retrySession()}>{busy ? "Έλεγχος…" : "Νέα προσπάθεια"}</button><button className="secondary-button" type="button" disabled={busy} onClick={() => void logout()}>Τοπική αποσύνδεση</button></div>{footer}</section></main>;
    return (
        <main className="auth-shell"><section className="auth-card"><header className="brand-row"><div className="basketball-mark">K</div><div><span className="eyebrow">KOMOBASKET OFFICIAL SCORER</span><h1>KomoControl</h1></div></header>{authState.kind === "blocked" ? <div className="blocked-panel"><h2>Η σύνδεση δεν είναι διαθέσιμη</h2><p>{errorMessages[authState.errorCode]}</p></div> : <><p className="intro">Συνδεθείτε με τον λογαριασμό scorer που έχει οριστεί στο KomoPlatform.</p><form onSubmit={(event) => void submitLogin(event)}><label>Όνομα χρήστη<input autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} disabled={busy} required /></label><label>Κωδικός<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} disabled={busy} required /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button" type="submit" disabled={busy || !username.trim() || !password}>{busy ? "Σύνδεση…" : "Σύνδεση"}</button></form></>}{footer}</section></main>
    );
}

export default App;
